Git Scribe
==========

The git-scribe tool is a simple command line toolset to help you use Git, GitHub and Asciidoc
to write e-books.  This provides tools for setting up the structure, collaborating with co-authors, doing technical and copy-editing, handling translations, taking errata, as well as publishing online, pdf, mobi (Kindle) and epub (iBooks, Nook) versions.

The project is targeted for writing books of any length, but should also be usable for articles and stuff too, though for a while you'll have to just do it as a really short book.

Features
========

Eventually, these are the feature goals for the project:

* Easy: Syntax-Highlighted Code, Formula, Diagrams
* Site Generation: Comment, Search, Permalinks
* Pegging versions of the book to versions of the tool it documents
* Technical and Copy editing workflow tools
* Translation workflow tools
* Selling (possibly): Kindle, iBooks, Lulu, Pledgie(?)

The idea is that you use the tool to generate a known structure, write in asciidoc and let the tool handle everything else for you.  I want authors to be able to focus on writing and not have to worry about anything else.

A good AsciiDoc cheat sheet: http://powerman.name/doc/asciidoc#_text

Disclaimer
==========

This tool is a work in progress.  At the 1.0 release, this file will be totally up to date, but for now I may have documented some stuff that doesn't yet work.  Contact me personally if you are interested in working on it.

Installing
==========

You can install git-scribe via RubyGems.

    $ gem install git-scribe

For local generation (evenutally pushing to GitHub will handle gen for you), it depends on a couple things like:

* Ruby
* asciidoc, a2x
* xslt stuff
* FOP for PDF gen

Usage
=====

Initialize a new book with `init`.

    $ git scribe init

This will set up the outline for your book.  All the book content goes into the 'book' subdirectory with 'book.asc' as the starting point.  If you want to split the writing up into multiple files you can simply include them in the book.asc file.

    $ git scribe gen [site|html|pdf|epub|mobi|all]

Roadmap
=======

See the_dream.asc for what this file should look like eventually.

